### ISSUE TITLE
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

### ISSUE THREAD

**Issue by pepsi7959** [pepsi7959/ProtocolBuffer-c#3]
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

No package 'protobuf' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by pepsi7959** [comment]
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/protobuf

**Comment by totszwai** [comment]
It should be **without** the protobuf:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by CooperLi** [comment]
> It should be **without** the protobuf:
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

It's working!
